spring.application.name=hospitalManagement

# DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/Hospital_Management_2026?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=56789A


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always



#What it does:------->>>
#
# Drops and recreates all tables every startup
#
# Builds schema from your Entity classes
#
# Executes data.sql after tables are created
#
# Prints formatted SQL in console
#
#For a tutorial project ?> this is perfectly fine.